### ISSUE TITLE
1.3.4 returns server error 505

### ISSUE THREAD

**Issue by drupadt** [mattbanks/woocommerce-local-pickup-time#35]
Hi Matt,

We've discussed ordering scenario before via email about how I wanted to stagger time for someone for pickup and I thin you implemented this on 1.3.3. It worked but then 1.3.4 came along and now when anyone clicks on checkout they are hit with 505 server error. Any idea what needs to be done?

**Comment by timnolte** [comment]
@drupadt I'll have to dig into this. I'm sorry to say that the versions starting with 1.3.2 since have introduced more problems than I had realized. That release should have had more testing before it's release but I knew that 1.3.1 had introduced a bug, and there was a significant feature in that release that the holidays kind of all delayed. I'm going to work on getting the next bug release out as soon as I can. Hopefully once the bugs get addressed I can get back to writing the automated tests that should help with preventing bugs like these from occurring in the future.

**Comment by drupadt** [comment]
Thanks Tim, for now is there any possibility of manually reverting to one of the older versions and activating that plugin?

**Comment by timnolte** [comment]
@drupadt you can go to the tags/releases and manually [download 1.3.1](https://github.com/mattbanks/woocommerce-local-pickup-time/releases/tag/1.3.1) and install it. Just make sure you don't have any auto-updating setup for your plugins.

**Comment by timnolte** [comment]
@drupadt can you provide your PHP/WordPress/WooCommerce versions, as well as any other WooCommerce-related plugins you have installed? I was unable to reproduce this issue in either of my testing environments.
