### ISSUE TITLE
Address JS package security vulns

### ISSUE THREAD

**Issue by mattbanks** [mattbanks/woocommerce-local-pickup-time#61]
A few packages have security vulns that we should address.

<img width="780" alt="Screen Shot 2019-11-19 at 9 43 25 AM" src="https://user-images.githubusercontent.com/302970/69156301-31402d00-0ab1-11ea-92ab-83d2e24ea2dd.png">

**Comment by timnolte** [comment]
Thanks for letting me know about these. I thought I had security notices turned on but perhaps not for this repo since it's owned by you, so maybe I don't get them. I need to get back working on this. Hopefully my new job will settle down soon so I can get back to making some progress on some of the open issues. I'll carve out some time in the next day or so to address this

**Comment by timnolte** [comment]
@mattbanks I turned on security alerts on my fork so I should get notified of these directly also. Thanks!

**Comment by mattbanks** [comment]
No worries dude! I haven't had any time for this lately and haven't even looked at WordPress for quite a few months now with everything else going on at work and home.
